# -*- coding: utf-8 -*-
"""calculation_of_3no.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QYQx7-BWonbbBIV-FDdq1yDQBf0sYEZi
"""



num1=int(input("Enter the 1st number:\n"))
num2=int(input("Enter the 2nd number:\n"))
num3=int(input("Enter the 3rd number:\n"))
cal=(num1+num2)*num3
if cal>100:
  print("Greater than 100")
else:
  print("Less than 100")