# -*- coding: utf-8 -*-
"""name_age_sex.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S_ndMCBD_wdKC_2GR8qSctMBICI7SMxj
"""



name=input("Enter your Name:\n")
age=int(input("Enter your Age:\n"))
sex=input("Enter your Sex:\n")
print("Name:\n",name)
print("Age:\n",age)
print("Sex:\n",sex)