# -*- coding: utf-8 -*-
"""odd_or_even.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zJMAtM-sq8CiBwRdZ90TLjjL91NWqJVP
"""



print("Odd or Even")
num=int(input("Enter a Number:\n"))
if num%2==0:
  print("Even")
else:
  print("Odd")