# -*- coding: utf-8 -*-
"""voting_elgibility.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1diZXDVqJQqTWgtEKbSWD8wcovGVJ4m7u
"""

print("Voting Eligibilty")
age=int(input("Enter your Age:\n"))
if age>=18:
  print("Eligible to Vote.")
else:
  print("Not Eligible to Vote.")